git ci: tell user (after the fact) that cancelled/failed commit => no push.

diff --git a/bin/git-ci b/bin/git-ci
--- a/bin/git-ci
+++ b/bin/git-ci
@@ -1,6 +1,8 @@
 #!/bin/bash
 # git-gui pops a dialog if it doesn't find spelling dictionary for current
 # locale.  Simpler to silence it (and I write English commit messages anyway).
-env LC_ALL=en_US.utf8 git citool &&
-git push --recurse-submodules=on-demand ||
-echo '`git push` failed.'
+if env LC_ALL=en_US.utf8 git citool; then
+  git push --recurse-submodules=on-demand || echo '`git push` failed.'
+else
+  echo Commit cancelled, so not pushing.
+fi
