git ci: automatically push to my forks [Beni]
Works for `hub fork` flow when upstream remote is `origin`
and my fork remote is `cben`.

diff --git a/bin/git-ci b/bin/git-ci
--- a/bin/git-ci
+++ b/bin/git-ci
@@ -53,7 +53,13 @@ if
     fi
   fi
 then
-  git push --recurse-submodules=on-demand || echo '`git push` failed.'
+  remote=()
+  if git remote show | grep --quiet --line-regexp 'cben'; then
+    remote=cben
+  elif git remote show | grep --quiet --line-regexp 'bpaskinc'; then
+    remote=bpaskinc
+  fi
+  git push --verbose --recurse-submodules=on-demand --set-upstream $remote || echo '`git push` failed.'
 else
   echo Commit cancelled, so not pushing.
 fi
